export const GET_MODAL_RESPONSE = 'GET_MODAL_RESPONSE';
export const GET_FORM_RESPONSE = 'GET_FORM_RESPONSE';
export const GET_ANALYZE_RESPONSE = 'GET_ANALYZE_RESPONSE';

export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE';
export const GET_SINGLE_RESPONSE = 'GET_SINGLE_RESPONSE';
export const ADD_NEW_USER_RESPONSE = 'ADD_NEW_USER_RESPONSE';
export const UPDATE_EXISTING_USER_RESPONSE = 'UPDATE_EXISTING_USER_RESPONSE';
export const DELETE_USER_RESPONSE = 'DELETE_USER_RESPONSE';

export const GET_BOOKS_RESPONSE = 'GET_BOOKS_RESPONSE';
export const GET_BOOK_RESPONSE = 'GET_BOOK_RESPONSE';
export const ADD_NEW_BOOK_RESPONSE = 'ADD_NEW_BOOK_RESPONSE';
export const UPDATE_EXISTING_BOOK_RESPONSE = 'UPDATE_EXISTING_BOOK_RESPONSE';
export const DELETE_BOOK_RESPONSE = 'DELETE_BOOK_RESPONSE';

