export const GET_MODAL_RESPONSE = 'GET_MODAL_RESPONSE';
export const GET_FORM_RESPONSE = 'GET_FORM_RESPONSE';
export const GET_ANALYZE_RESPONSE = 'GET_ANALYZE_RESPONSE';

export const GET_RESPONSE = 'GET_RESPONSE';
export const GET_SINGLE_RESPONSE = 'GET_SINGLE_RESPONSE';
export const ADD_NEW_RESPONSE = 'ADD_NEW_RESPONSE';
export const UPDATE_EXISTING_RESPONSE = 'UPDATE_EXISTING_RESPONSE';
export const DELETE_RESPONSE = 'DELETE_RESPONSE';
